### ISSUE TITLE
Add XAML Support to the UI Library for easier customization and faster edits by UI designers

### ISSUE THREAD

**Issue by HeadClot** [space-wizards/RobustToolbox#1003]
Hey,
I am opening this discussion to talk about the possibility of XAML support for UI system in the Robust Toolbox.

_Why am I suggesting this?_
- Currently the current User Interface System relies on nested classes and makes it hard for customization from a UI designers perspective.
- It does not have any WYSIWYG UI Layout editor. Which makes even more complicated from a UI designers perspective.

_How can we solve this?_ 

- Adopt XAML for editing the User Interface / GUI for the Robust toolbox.
- As for the Editor as for the WYSIWYG UI Layout editor Currently Visual Studio has a built in XAML UI Editor called Blend however there are also plenty of other third party XAML UI editors that can export XAML. Most are free or low cost as well.

_What is XAML?_
XAML is a markup language originally made for Microsoft's Windows Presentation Foundation UI library. That said I am not advocating we switch to WPF but adopt the XAML markup language for easier and faster editing of various User interfaces in the project.

**Comment by PJB3005** [comment]
Using XAML for the purposes of "having better editor integration / a visual editor" is EXTREMELY unlikely.

My understanding is Avalonia has to basically rewrite the XAML IDE support inside Visual Studio from scratch for their plugin, because VS' native support cannot be extended. I'm also 99% sure ReSharper/Rider has it hardcoded in by JetBrains and I doubt they'd do that for us if we used it. (and even that is pretty broken, I believe the launcher is in a permanent state of "error" due to XAML issues in Rider which makes it rather annoying to develop)

Not to mention the effort of supporting a visual editor inside VS. It's more likely we'll make a visual editor in the client itself than embed the client into something like VS for a visual editor.

XAML is also intended to map 1:1 to .NET objects I believe, which isn't necessarily... elegant. I believe it also implies complex stuff like data binding in the spec (though of course we could always ignore the spec) which would be incredibly painful to implement ourselves.

I do agree we need some kind of templating language that isn't "object initializers in C#", but I'm not sure XAML is unambiguously a great fit.

**Comment by ghost** [comment]
On the topic of alternative markup languages for UIs, I was talking with Q#4344 on discord yesterday about him possibly porting the necessary libraries to allow native SVG interfaces using attributes/tags in the XML for callbacks/embedding elements like lists and whatnot.

I think that'd be the best possible UI system if he follows through with it or someone else implements it. Directly rendering SVGs means UI designers would be able to use robust editing tools available through programs like Inkscape and Illustrator to make basically whatever UI design they want and it'd be extremely easy to add functionality to UIs built through this theoretical system since you would just have to add the relevant attributes to a shape/path.

**Comment by PJB3005** [comment]
I... don't see how SVG as a UI format would be a good idea, at all.

The proposed positive is that we can use "robust editing tools". But uhm, Inkscape would be absolutely godawful to make UIs in.

Inkscape is not meant for UI development. Sure you can definitely make *mockups* in it easily but when actually developing finalized UIs you want significantly better tools so that you can:

1. Easily re-use standard controls that are automatically styled.
2. Have correct appearance matching the engine.
3. Have sane automatic / responsive layout rules like WPF / SS14 UI system.

As far as I know, *no tool* exists that will magically be a good fit for this, SVG or not. Now obviously things like WPF's visual editor inside VS fits the bill but *we can't use that*.

Rendering SVGs in-UI is definitely convenient yes, but it would also add a significant amount of technical complexity to the UI system and renderer, on top of being not always desirable (using pre-rendered textures is almost certainly cheaper to render when you consider things such as AA having to be done)

Also, some of the features you describe like being able to easily wire up tags... we could implement such systems into the current UI system already. I would definitely like to implement better UI features like this (especially surrounding styling) but I have my hands full right now.

**Comment by HeadClot** [comment]
PJB3005: That sucks to hear about XAML but It is good to know for the future. :) 

Anicentpower: I honestly did not think about XML. Happy that some one thought about it. :)

**Comment by PaulRitter** [comment]
fixed :) pls close
