### ISSUE TITLE
ImageSharpExt.GetPixelSpan does not work reliably.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1184]
Large enough images will totally still be segmented internally and contrary to Q's claims, the method will not ensure a contiguous buffer is used. Instead an exception simply gets thrown.

**Comment by Tyler-IN** [comment]
Was correct at the time.
They released 1.0 and there's a TryGetPixelSpan.

**Comment by PJB3005** [comment]
> Was correct at the time.

Completely false. The code in imagesharp at the exact tag we're at does `.Single()` on the memory groups which will trivially fail if there's more than 1. We also haven't updated the NuGet packages yet I ran into this exact problem a while ago while messing with large images.

> They released 1.0 and there's a TryGetPixelSpan.

Which, as the name implies, *tries* but can fail.

**Comment by Acruid** [comment]
Appears to be fixed by using `TryGetSinglePixelSpan` in e68c5b47e739f5cb02130aba42fb7046dc9b7d5e. The nuget package was updated on Feb 17, 2021 and there is no `.Single()` in the current decompiled function. The TryGet will still fail if there is more than one memory segment.

Whatever is going on with this function, it seems to be working fine for the last ~9 months, so there is no reason to spend more time on it. If there is anything more to this than PJB and Q trying to 1up each other, make a new issue.
