### ISSUE TITLE
Add support for OpenGL ES 2.0

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1251]
And then use ANGLE on Windows.

This will allow us to basically run on any GPU you can think of.

Problems that we'll need to solve:

1. check if there are any issues with GLSL support.
2. Probably rewrite all the shaders to support both ES 2.0 and sane GL.
3. Fall back to crappy lighting framebuffers due to lack of floating point render targets.
4. Work with lack of UBOs.

**Comment by PJB3005** [comment]
See #1266

**Comment by 20kdc** [comment]
I would consider this issue effectively closed with some minor limitations regarding some required extensions. However, outside of mobile devices (which was never going to work out anyway because bugs), the only problem so far is keeping the code from getting updated in a way that breaks things. It would be good to have some sort of standard ES2-only testing environment.

**Comment by PJB3005** [comment]
That would probably fall under a bigger issue of testing rendering so... closing.
