### ISSUE TITLE
EntityQuery using WorldPosition to determine match

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/RobustToolbox#1341]
https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Shared/GameObjects/EntityQuery.cs#L127

shouldn't it rather look for collision?

**Comment by metalgearsloth** [comment]
It should probably use Intersects.

There's a few other things on the entity manager that only checks position. I assume it was for perf reasons at the time?

From what I can see there I wouldn't use it as is because it looks like it'll iterate over every single entity and check its position (all 4,400 of them...)

Better off calling GetCollidingEntities from the physics manager probably, or alternatively using the grid-tile lookups which are fast.

**Comment by PJB3005** [comment]
If you need proper physics intersection you absolutely want a separate query type for that anyways. The least of the reasons for that being support for collision groups and such.

Comparing worldposition is done because it's fast, which is one of the things you want for this query type (e.g. PVS)

**Comment by PaulRitter** [comment]
makes sense. i guess lockers should be refactored to use `GetCollidingEntities` like sloth suggested

**Comment by PJB3005** [comment]
Yes, they should.

**Comment by Acruid** [comment]
Seems resolved.
