### ISSUE TITLE
Predict more physics stuff

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1374]
Currently only the player is predicted but more stuff needs to be predicted to reduce jankiness as your ping goes up. At the moment the lack of prediction on the pulled entity means it immediately "breaks" client-side because it gets too far from you.

Ideally potentially every physics entity should be predicted? At least if we can get the physics performance faster, especially given the client only cares about its immediate vicinity.

**Comment by 20kdc** [comment]
The physics performance, combined with the performance of physics prediction, makes this... kind of a relatively bad idea
Rather than predicting more, don't predict things that are "too" physics-dependent?

**Comment by metalgearsloth** [comment]
Performance is still a WIP but physics on the live server is currently unplayable IMO.

**Comment by PJB3005** [comment]
Only predict stuff the player is interacting with like objects being pushed/pulled. The rest should not be predicted both due to performance and, well, unpredictability.

Unrelated but I'm 99% sure SOMETHING is up with physics client side that makes it run more than it should. I think entities moving on conveyor belts cause client CPU load when they shouldn't.
