### ISSUE TITLE
[ServerConsole] restartserver doesn't restart "enough"

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#147]
If the server is memory leaking, i'd expect to be able to run this to cleanup all the things.
Doesn't seem to do that.

**Comment by PJB3005** [comment]
Restart probably just resets state to lobby and such.

**Comment by psykzz** [comment]
Also needs to clean up network connections imo

**Comment by psykzz** [comment]
If the command is being run from the console its a "hard" restart, kill and restart almost
If an admin is running, it should be a soft restart (resetting the state)

**Comment by PJB3005** [comment]
Marking this as in progress since @Muncher2112 is working on it.

**Comment by Muncher2112** [comment]
This doesn't crash now, but it doesn't do nearly as much as it should.

What should be getting cleaned up/reset on restart?  What (if anything) should be functionally different from just quitting and running thew .bat again?

**Comment by PJB3005** [comment]
Restart should probably reset the map, everybody's player status and go
back to lobby.

Essentially restarting the game state but keeping main systems alive to not
have to reinitialize everything.

On Jul 13, 2017 02:40, "Matthew Walker" <notifications@github.com> wrote:

This doesn't crash now, but it doesn't do nearly as much as it should.

What should be getting cleaned up/reset on restart? What (if anything)
should be functionally different from just quitting and running thew .bat
again?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/space-wizards/space-station-14/issues/147#issuecomment-314936707>,
or mute the thread

**Comment by PJB3005** [comment]
This command doesn't exist anymore. It's been replaced by `restartround` in content pretty much.
