### ISSUE TITLE
Rotation?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#149]
Allow the station to rotate relative to other things? Could be important to consider right now.

Issues will probably be sprite perspective though.

**Comment by ghost** [comment]
Wouldn't that utterly destroy our sprite work unless we use projected 3D models ?

A parallax would be much cheaper, we're implying that the station always stays in the same orientation relative to the game plan

**Comment by BobdaBiscuit** [comment]
I honestly would be fine with perspective getting mucked up by grids being able to rotate.

**Comment by ghost** [comment]
The issue is, how are we gonna make it look correct ? At all ? In 2D at least

**Comment by PJB3005** [comment]
That's the problem: I have no real idea.

That's why I'm making this issue.

**Comment by BobdaBiscuit** [comment]
I'm unsure how it would actually look but perhaps sprites could be rotated by the client so they are as close to normal as possible, but still aligned with the grid.

I'm too tired to explain/think it out properly but say the grid is rotated 75 degrees and you're looking into it from the outside, all sprites inside would be rotated 90 degrees so instead of being 75 degrees off it's 15. Anyone inside the grid has normal sprite rotation and the dude outside is rotated -90 degrees.

**Comment by ghost** [comment]
I honestly think it's going to be impossible to dynamically rotate anything in the game without 3D sprites. A good example is the human character. It's a 3D model

We can have "fake rotation" like DM does, per 45 degrees and have 4 directional sprites, but it's not going to be a smooth transition

**Comment by psykzz** [comment]
I'd like to support the 8 cardinal directions, and leave the station facing one way.

**Comment by h3half** [comment]
If I recall correctly, the original reason (well, the reason on the original forums anyways) there were eight cardinal directions instead of arbitrary rotation was because it would be too difficult to add new items. If you require any new item to have an actual 3D model, that means someone has to make a model for that item (duh). Making a sprite is, generally, much easier than making a model and a texture to put on the model.

~~Additionally, you have to consider polygon counts. Presumably most "vanilla" models would be somewhat optimized, but what happens when some random server wants to make a new model for an energy ball (or whatever) and uses 10,000 polygons to make a perfect sphere? Maybe that's not the best example, but I think that was the essential thrust of the argument for sprites over models.~~ This is probably irrelevant

Even though the original dev team did have some 3D models, those models were actually just used to export eight 2D sprites for use in the game. I forget the exact reason they did that, I think it was to make it easier to prototype objects without drawing eight versions of everything, but there was definitely a Blender or Maya plugin floating around that exported the model as isometric in eight directions.

A good example is a toolbox - you might have three different colored toolboxes, each with two states (open and closed). That's 48 sprites. Or, you could make one model, recolor it, export the sprites, then adjust it to be flipped open and export again. At the end of the day you still have 48 sprites, it's just easier on the artist.

Anyways that's just a long way of saying I agree with @psykzz because requiring 3D models might be a barrier to entry for content creators. There are still ways to incorporate 3D models in your workflow and get a 2D result, but increased rotation brings increased complexity.

**Comment by ghost** [comment]
So yeah, 8 directions seems like the best we can get. At least it's four more directions than SS13 -usually- handled

The sprite work will already be immense, even once our project looks like it's actually viable and we open the content floodgates

Finding or training people to use Blender to make half-decent models (especially for free) would be a herculean task

**Comment by ZoldorfTheWizard** [comment]
Transformations of the station would be handled at the engine or sprite level. you could draw everything you want to a render target then proceed to rotate the render target to achieve this effect.
