### ISSUE TITLE
Need replicated nullspace map between server and client

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1592]
Blocker for PVS refactor. You don't need to replicate the *actual* entities on it you just need to make the server + client aware of the same map (and server needs to be able to tell the client when entities are nullspaced).

https://discord.com/channels/310555209753690112/770682801607278632/811925385033809980

**Comment by Acruid** [comment]
Could you use another mapID for the PVS cache instead of Nullspace?

**Comment by metalgearsloth** [comment]
TBH I just need a way to notify the client when the MapId should be nullspace (currently the component state just sends the parent and not the MapId) so I'm all ears to any suggestions.

**Comment by Acruid** [comment]
If all you need to do is tell the client that an entity left the PVS using the MapID, could you do something like set the high bit to 1 as a flag for outside PVS, like we do for client entity IDs?

Pros:
* easy bit check to tell if an entity is in PVS or not (mapID & 1 << 31) != 0 (see EntityUid.IsClientId, same benefit as nullspace)
* the other 31 bits still contain the real mapid, which would be useful for telling where an ent originated from (auto cleanup when deleting the real map, server does not even need to tell the client to individually delete each entity, not possible if you use nullspace for every entity)
* Any code not aware of PVS will blindly check for equality, since this is two exclusive ranges of ids PVS maps will never equal regular maps, so nothing will break and you don't have to explicitly check for PVS (same benefit as nullspace)
* don't have to do any sort of networking, just craft the special ids and send them in the transform, effectively teleporting them between maps, which we already have full capability of doing (same benefit as nullspace, but without having to mess with nullspace networking)
* When they come back into PVS just teleport them back to the real map by removing the high bit flag (client can literally do this on it's own if the entity has not moved, like with walls, because the entity still knows what real map it should be on, and the coords have not changed, massive win over nullspace)
* You don't even have to change anything, except maybe a few spots of code to deal with the new PVS mapIds (like pause the PVS map when client makes it, don't throw exceptions about missing PVS maps and autogenerate them instead, little more work than nullspace, but should not be much)

Cons:
* varint packing will be worse in net messages for netIds, but there might be ways to get around this
* we only have 1 billion map ids available instead of 2 billion (half PVS maps, half real ones), like this even matters
* ???

**Comment by metalgearsloth** [comment]
I'll give it a try and do it in a separate PR with our current PVS.

**Comment by metalgearsloth** [comment]
So how is stuff like RenderingTreeSystem handled? Would they still be stored under the original MapId and then filtered out through something like ProcessSpriteEntities?

**Comment by Acruid** [comment]
All you are doing is teleporting the entity from map 0x1 to map 0x8000_0001, and map 0x8000_0001 is paused, so this is the same exact case for any entity that would be on another map from the current one. Entities on other maps should not even be considered when drawing the viewport.

**Comment by Acruid** [comment]
Using nullspace and MapId as a way to hide movers outside PVS are both really lame workarounds. These two solutions would basically desync the transform from the server, either changing the mapid or the parent entity. The MapId value isn't even sent over the network.  We need a better solution to https://github.com/space-wizards/RobustToolbox/issues/1210.
