### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#160]
How do we want to handle automatic updates?
Do we want the client to self update?

**Comment by PJB3005** [comment]
Auto updating might be kind of iffy because we want version compatibility between client and server, so if the client auto updates and the player's favorite server hasn't yet he'll be kinda screwed.

Make it easy to update but not automatic I'd say.

**Comment by psykzz** [comment]
I agree give them the option to say no, but yeah we should just make it easy to update the server too.

A lot of other developers have the same issue, its not uncommon to have the client patched before the server.

**Comment by PJB3005** [comment]
Can't guarantee that the server will be able to update easily due to code incompatibility with the content assemblies and such.

**Comment by h3half** [comment]
Might be better to have the ability for the client to tell the user "Hey there's an update! Make sure you have the same version as your favorite server!" on like the main menu. Maybe it could just check the client's version against the version in this git repo or something to see if there's something newer.

That way the user is aware that an update is available, but has to go out of their way to get it. With a proper warning in-game they'll know not to update until they've checked their favorite server(s).

It also might be worth making previous/legacy releases available on this project as downloads, in case someone plays on multiple servers with different versions, or a server has to roll back a version, or whatever.

**Comment by gbasood** [comment]
I think auto updates should only probably happen if/when we find a proper way to distribute them
For now, checking github via API for new releases and notifying the user with a link to the releases page is fine

**Comment by psykzz** [comment]
^^ exactly what i had in mind tbh.
I just think the client should have a way of doing this without requiring user interaction.

**Comment by Acruid** [comment]
It is not feasible to expect compatibility between versions of the engine. The version of Robust to use is based on what the GamePack was built against. Therefore we cannot force/auto update the server or client. We will distribute the engine updates like Minecraft's Forge program, where the launcher pulls the required version for a given GamePack.

It should require no input from the user to do this. Typical use will be the user selecting the server they want to join, the launcher downloading the GamePack from some remote location, the launcher downloading whatever version of the client is needed for the GamePack, and launching the Client to join the server.

Pros: A GamePack will always work forever, the server won't break when a new version of Robust is released, no downtime where a client is waiting for a server to update their GamePack, and server coders can update their GamePack at their leisure.

Cons: Servers will only update their GamePack when there is a cool new engine feature, and we cannot force all servers up to date.

Since this issue is two years old, i'm closing it. If you want to discuss this more, do so in the Discord.
