### ISSUE TITLE
Quit button in the pause menu crashes the game

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#170]
Explicit, debugging reports a stack overflow

**Comment by h3half** [comment]
I tried debugging this but hit a wall because I don't know much.

The actual error happens on line 279 of CollisionManager.cs, after the Quit button is pressed:
```
277    public void RemovePoint(CollidablePoint point)
278            {
279                if (_points.Contains(point))
280                    _points.Remove(point);
281            }
```
The game is in the process of deleting entities. Using the default (server-generated) map, the first thing that triggers this code is a door, but I don't think that matters.

I think the error on 279 is that the Contains() function only works on strings (unless I read MSDN wrong, or unless this isn't the standard Contains() function, or really anything else). When I change it to this:
```
if (_points.ToString().Contains(point.ToString()))
```
line 279 works just fine.

However, then the stack overflow just happens one line later, on 280. I don't know how to fix that, or even if my "fix" to 279 did anything.

Regardless, I'm fairly certain line 279 is what's throwing the exception. Past that is anyone's guess really.

EDIT: Turns out psykzz already has a PR that mostly fixes this. Oh well, at least I traced the overflow to the right spot

**Comment by ghost** [comment]
There's a PR up that intends to fix that at #171

**Comment by psykzz** [comment]
This actually happens because of a legit stackoverflow.

The number of times we do` IocManager.Resolve<Thing>.Shutdown`
Which does 
```
foreach(var comp in components)
    comp.Shutdown()
```
which then does fucking 
```
foreach(var comp in components)
    comp.Shutdown()
```

Is causing the stack to just grow to large, we've instead moved to dispose them all a little better (there already was the functions). but we found that its not working 100% as it should and its breaking in the collision manager right now.

I've found that some entities are not being cleaned up or losing an owner when the system reconnects and so when you move the AABB collision detection fails.

If you want to provide any help, #171 has a bunch of changes most them don't actually help, as it was all just me testing. Ill go through today and keep only the stuff that actually helps so that you can use it if you want to help with debugging @h3half.

**Comment by h3half** [comment]
#171 fixes this and uncovers new bugs as well. Those should probably get their own issue.
