### ISSUE TITLE
Directed eventbus should also work with ComponentReference

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1730]

**Comment by Acruid** [comment]
Can you describe how this is expected to work. What happens when something subscribes to ITransformComponent and something else subscribes to TransformComponent? When ITransformComponent is unsubscribed, would it also unsubscribe TransformComponent? Which of these is invoked when a directed event is sent?

**Comment by metalgearsloth** [comment]
I'd say anything that's a reference from the componentfactory gets invoked, so ITransform and Transform. The only problem is if something subscribes to both the original and the reference which shouldn't be done (which we'd probably need a test for at some stage).

**Comment by Acruid** [comment]
Performance wise this would need to not increase the cost of dispatching an event. `EventTables.Dispatch()` would need to be unchanged or made faster. Looking at the layout of the data, it seems like this proposal would be compatible with that, and would just increase the memory use of the EventBus. It already has the for loop required for making the one:many relationship of interfaces work, so time complexity should not increase.

"Don't do it" isn't really a great solution to the problem of ComponentReference subscription collisions, and they would only be discovered at runtime (or some sort of complex static code analyses) due to how the EventBus allows dynamic subscriptions. If a system subscribes to TransformComponent, it's going to block any system in the future from being able to subscribe to ITransformComponent. More interfaces does not solve this issue. The eventbus does not allow directed subscriptions to change while the server is running, so any collisions should be caught early during initialization.
