### ISSUE TITLE
Configuration Manager doesn't have a way to unsubscribe from OnValueChanged.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1743]

**Comment by Acruid** [comment]
What do you need this for?

**Comment by gradientvera** [comment]
For cleanup. OnValueChanged subscribes to a C# event.

**Comment by PJB3005** [comment]
What are you cleaning up, here? You really shouldn't be registering non-singleton objects to it.

**Comment by gradientvera** [comment]
Sadly right now a **LOT** of EntitySystems register to it, and imo they should unregister on shutdown

**Comment by Acruid** [comment]
The original design idea was that IoC Managers subscribed once for the entire lifetime of the running program, and you don't need to unsubscribe since you just disposed the DI container when the program shut down.

Right now EntitySystems are in a weird spot where we pretend they have a different lifetime than the program, but you are not allowed to dynamically add/remove them during the lifetime of the program. I think we need to decide if they should have the same lifetime as the EntitySystemManager (and therefore the DI container/entire program), or if they can be dynamically started/stopped during the program life. The whole "shutdown/cleanup" idea of having to unsubscribe from things immediately before the program closes is pretty pointless.

**Comment by gradientvera** [comment]
It's tricky. For the client, the lifetime of EntitySystems is very clearly "as long as we're in-game", but for the server it's much more ambigous as you pointed out.

**Comment by metalgearsloth** [comment]
Done in https://github.com/space-wizards/RobustToolbox/commit/719ea26a31c40e7c7748d8c34b3458687d643604
