### ISSUE TITLE
Console exception spam closet boogaloo

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/RobustToolbox#2109]
I was messing around with lockers with someone else. Doing some open/close spam my character was sort of "strafing" around, I checked the console and it was spamming these exceptions. After I somehow fixed it, when I tried to pull the locker, It causes a nan and went back to normal.
![unknown](https://user-images.githubusercontent.com/43253663/136501621-8ade6862-a838-4778-885a-d74e4cf1efae.png)

![unknown](https://user-images.githubusercontent.com/43253663/136501636-ff8bf77c-b244-4188-9100-e0c73c2d8a68.png)

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/136505309-eecd9492-f629-45d5-b904-862a9f27e5fe.png)

**Comment by DogZeroX** [comment]
https://discord.com/channels/310555209753690112/790656972801572905/895897958975950848 
Here's the discord image, if only i was capable of copypasting from console :smilethink:

**Comment by metalgearsloth** [comment]
My guess is because I never implemented breaking properly it cascades into the allocated island being fucked so the real reason is how the force became NaN (I'm guessing one body had a NaN pos and the other didn't). Given we can have joints extending across PVS (and PVS is not aware of this primarily because holy fuck it's already expensive) it's probably just easiest to make the island builder check for NaN (or separate map in the future).

**Comment by PaulRitter** [comment]
bruh at what point do we just have pvs not use nans this is cancer

**Comment by metalgearsloth** [comment]
> bruh at what point do we just have pvs not use nans this is cancer

When you co-
