### ISSUE TITLE
AppearanceComponent doesn't reconcile properly after mispredicts.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#2127]
Right now, `Appearance` data isn't reconciled at all when the client mispredicts. This can cause *hilarious* effects in SS14 such as mobs staying horizontal forever when slipping mispredicts, etc.

**Comment by ElectroJr** [comment]
In the case of the standing-state / slipping mispredict, I think the issue is due to the combination of:
- In `RotationVisualizer`, if the appearance component has no `RotationVisuals.RotationState` data, then the visualizer does nothing.
- The `StandingStateComponent`/system do not set any appearance data on init.

The result is that if a client mispredicts a slip, then the client set the appearance data and their (non-net-synced) sprite gets rotated. But when the server state comes in, it has no rotation state data so the visualizer never resets the sprite rotation.

So in order to fix this issue in general, either visualizers need to consistently apply a default state when `AppearanceComponent.TryGetData` fails, or server/shared systems need to set some default appearance data on init. I'm leaning towards the former, because I think it will result in less boilerplate.

**Comment by ElectroJr** [comment]
Okay so after looking into this more, while the above is part of the problem, something else is also wrong. AFAICT the other problem is that when handling the appearance component state, it simply sets the components dictionary equal to the state's dictionary, instead of cloning it. This means that when then modifying the component during prediction, it is also modifying the most recently received server state, so if the component resets & no new state came in, then it always "resets" itself to its own current state.

This general issue of directly using a state's dictionary is probably also responsible for space-station-14/issues/4956
