### ISSUE TITLE
Fix shadows

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#216]
Shadows have been turned off / removed until we can figure out what their problem is.

**Comment by ZoldorfTheWizard** [comment]
Hello yes graphics wizard from many timezone's here  

Lights get rendered six at a time and then blended together.
In this example here the black squares are the occluders (walls or anything that blocks light) and the orange line with the grey areas are the shadows. 

The first set of red lights gets rendered correctly with their shadow counterparts. 
![first six lights](https://cloud.githubusercontent.com/assets/7108570/26534968/681f66b8-43e6-11e7-879d-f08abd51acb2.png) 

Looks good right? Now look at what happens when you render another six lights: 
(pink are the new set of lights and green is where they actually end up at)
Note that I did not draw the shadows here for the new lights. 

![next six](https://cloud.githubusercontent.com/assets/7108570/26535062/3cf53048-43e7-11e7-8f93-a126227a1ee5.png)

After some debugging, the lights and the shadow map render everything correctly but the end texture that gets blended into the previous shadows gets flipped vertically!

Turns out that somewhere in sfml during rendering something causes it to flip vertically. 
This will happen for every even set of lights. (IE the second set, the fourth set, the sixth set... and so on)

I bandaided the issue by unflipping the even textures but performance took a huge hit because of it.
It also looks like linux/macos sfml will segfault randomly due to the bandaid. 

The entire lighting stack was disabled here 0730545 to stop the segfaults temporarily. 

If this interests you here is more reading material on the closest thing on our lighting system: https://github.com/mattdesl/lwjgl-basics/wiki/2D-Pixel-Perfect-Shadows

**Comment by d34d10cc** [comment]
Is this another case of Texture.CopyToImage()?

**Comment by ZoldorfTheWizard** [comment]
The fix is, Yes :(

**Comment by ZoldorfTheWizard** [comment]
We currently have six lights max as a quick fix. still a issue though.

**Comment by PJB3005** [comment]
G O D O T
