### ISSUE TITLE
Unit used for distances?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#252]
Global world coordinates, that is.

Currently the distance unit is (as far as I know) not actually defined as meters or such. To make sure we're all consistent about everything we should obviously define it as something.

First idea of obviously meters. Problem with that is, grid tiles wouldn't be 1x1 meter large (that's too large to work with, SS13 looks really ugly because of it). They'd be closer to like, 0.5 or 0.33.

Now the problem with that is, you can't just "fetch the next tile" anymore by adding `1` to your x axis. It's a minor usability concern but I figured it'd be worth making a thread about.

I feel that we should still go with meters and just live with it that one tile is NOT one meter.

**Comment by Acruid** [comment]
Are we associating world units with tile indices? When thinking about the speed of something, would you say "I want the object to move 2 tiles/sec.", which would depend on knowing the size of tiles, or would you want to say "I want the object to move 2wu/sec".

Dissociating tile indices from world units would allow the scaling between tile indices and world units to be completely handled by the render or map manager, and transparent to all other code.

**Comment by PJB3005** [comment]
Personally I would like it if grids could define their own tile size.

**Comment by Acruid** [comment]
There is no problem with grids providing their own constants for converting between world units and tile indices, because there will be code that needs to convert between the two. The main point is that code needs to not make the assumption that 1 tile = 0.5wu or 1 tile = 0.33wu. Or worse, what is happening in the codebase right now, with code assuming 1wu = 32px.

As for defining the world units, they can easily be defined as 1wu = 1 meter, or you could just call them meters, or you could go the kilogram route and not define it as anything and pull the conversion out of thin air.

**Comment by Acruid** [comment]
Everything is using `CluwneLib.Camera.PixelsPerMeter` property to convert Screen Units (Pixels) to Game Units (Meters). The default is `1m = 32px`. This is basically the camera "zoom". Each grid can specify the scale of their Tiles in word units using `IMapgGrid.TileSize`, with the default being `1 Tile = 1m`. Changing this to less than one makes the tiles smaller relative to the entities and camera zoom. Pretty much like Small and Large grids in Space Engineers. All entity positions are measured in meters.
