### ISSUE TITLE
Config value hook attribute

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#257]
Right now some configuration hooks are done pretty poorly, hardcoding and one-time initialization is everywhere. Ideally we'd be capable of editing most config values at runtime, except maybe complicated ones like server port.

I'm thinking a system like this:

```cs
public class SS14NetServer
{
    private ushort port = 7777;
    [Configurable("net.port", 7777, ConfigPortAccess)]
    public ushort Port
    {
        get => port;
        // Config hook can override private accessor.
        private set
        {
            // If we're already running don't allow port change.
            if (loaded) { throw new InvalidOperationException(); }
            port = value;
        }
    }
    public ConfigPropertyAccessFlags ConfigPortAccess() => loaded ? ConfigPropertyAccessFlags.ReadOnly : ConfigEditAccessFlags.ReadWrite;
}
```

So my idea is this:
`ConfigurableAttribute(string key, object default, Func<ConfigPropertyAccessFlags> AccessChecker)`: marks a property as configurable. It will be automatically set with the new value if the config value changes (for one reason or another). Parameters are this:
* `key` the key in the config file to link to.
* `default` a default value that we can create a new config file from.
* `AccessChecker`: a function that should return a `ConfigPropertyAccessFlags` saying how this thing can be accessed. This can be useful for more intuitive config and reasoning UI side for example.

`enum ConfigPropertyAccessFlags`:
* `ReadOnly` Can only be read
* `ReadWrite` Can be both read and written.

@Acruid the config system's all yours, what do you think?

**Comment by Acruid** [comment]
Right now the 'proper' use of the configuration system is something like:
```C#
class foo
{
    private IConfigurationManager _cfgMgr;

    public foo(){
        cfgMgr = IoCManager.Resolve<IConfigurationManager>();
        cfgMgr.RegisterCVar("net.port", 1212, CVarFlags.NONE);
    }

    public int Port {
        get => cfgMgr.GetCVar<int>("net.port");
        set => cfgMgr.SetCVar(value);
    }
}
```

Each system should be managing it's own CVars, and other systems should not be querying them. I think Net.Port is the biggest offender of this right now, spread over like 3 systems. I went with the centralized dictionary system with Get/SetCVar so  that when the value is changed it can easily be replicated over the network or blocked by the config manager.

I also wanted these available to the Console, so that the user can work with them. Traditionally in Quake-like engines CVars are children of console commands (verbs), so they should have an optional OnChanged callback function when registered. I was planning on making that happen in the future. The CvarFlags pretty much cover read/write protection and replication behaviors.

Your design is quite nice though, it really enforces the idea that these are properties of the system that owns them, not global variables. I would like more people to express their opinions about this.

**Comment by Cyberboss** [comment]
As a third party looking into this issue, I much prefer the way @PJB3005 laid it out. There can be no mistaking where a var is from if it's defined in place. Relying on a string key lookup every time it's read isn't concrete enough to stave off misuse of it. My 2 cents

**Comment by Cyberboss** [comment]
`AccessChecker` is an impossibility sadly: https://stackoverflow.com/questions/8463657/how-do-you-put-a-func-in-a-c-sharp-attribute-annotation

**Comment by PJB3005** [comment]
Guess we'll need to go with using reflection names for it. Guess `nameof(checker)` and then use reflection to invoke it will have to be the way.

**Comment by PJB3005** [comment]
I'm gonna implement this but much simpler.
