### ISSUE TITLE
Scripting language used for tooling and as hard build dependency.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#261]
So the problem is that to do things like git hooks, `buildResourcePack` and other things need to be written in a certain language. Of course, Windows is a pile of crap and can't standardize so we can't just assume everybody has Python or bourne shell installed.

So what do we do?

We can either say "nope, Python is required to build" and just give people a link to the installer for Python 3. But people like @clusterfack disagree with this.

Or we'll have to maintain build scripts, etc... in multiple languages, which is a pain in the butt.

What do we do?

I still advocate going with Python 3 and telling people to get off their butt to install it, it doesn't take that long.

**Comment by agrecascino** [comment]
+1, people who can't install Python probably shouldn't code.

**Comment by clusterfack** [comment]
https://stackoverflow.com/questions/5458048/how-to-make-a-python-script-standalone-executable-to-run-without-any-dependency

**Comment by PJB3005** [comment]
Compiling Python scripts like that is just gonna bloat the Git history incredibly quickly, which I'd like to avoid.

**Comment by clusterfack** [comment]
I highly doubt it will make a noticeable difference

**Comment by PJB3005** [comment]
Run `buildResourcePack.py` through it and we'll see.

**Comment by psykzz** [comment]
Why do we even have the buildresource.py?
Can we not just have the zip hosted and downloaded? Ideally automatically from the client (customizable in config).

Why does this even need to be a step in the server repo

**Comment by psykzz** [comment]
If we have to keep it I'm okay forcing python 3 for our build third party scripts

**Comment by PJB3005** [comment]
`buildResourcePack.py` isn't the only thing that'll need it. It's just an example.

**Comment by elwray** [comment]
1. What you think about Bash or Shell? This scripting system built-in Mac and Linux OS. On Windows I use "Git for Windows" and this scripting systems present there too in "...\git for windows\usr\bin" folder.
I think this is good cross platform solution. But in this case user should add binary folder ("...\git for windows\usr\bin") to system paths. On Windows 10 user can install "Bash on Ubuntu".

2. Or we can use MSBuild for our purposes. It's cross platform and shipped with .NET Core. (https://github.com/Microsoft/msbuild) And in the future maybe project will be moved on .NET Core. I'm vote for this solution 👍

**Comment by PJB3005** [comment]
1. I'm fine with shell but there's a few problems, namely the fact that the default set of UNIX tools included with git is incredibly small, and it doesn't even come with ones like `bc`. It's possible but not pleasant. Second of all there's the issue that we need to be capable of locating the git installation and Mingw reliably.

2. I'm not sure msbuild is powerful enough for our purposes, and it isn't exactly a scripting language you'd use for common scripts, especially complicated ones.

**Comment by theOperand** [comment]
Python 3 gets my vote. Anyone compiling our code is already installing VS,
Python is trivial in comparison.

Op 7-jul.-2017 10:27 schreef "Pieter-Jan Briers" <notifications@github.com>:


   1.

   I'm fine with shell but there's a few problems, namely the fact that the
   default set of UNIX tools included with git is incredibly small, and it
   doesn't even come with ones like bc. It's possible but not pleasant.
   Second of all there's the issue that we need to be capable of locating the
   git installation and Mingw reliably.
   2.

   I'm not sure msbuild is powerful enough for our purposes, and it isn't
   exactly a scripting language you'd use for common scripts, especially
   complicated ones.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/space-wizards/space-station-14/issues/261#issuecomment-313620710>,
or mute the thread

**Comment by PJB3005** [comment]
Silver decided on Python 🐍.
