### ISSUE TITLE
Serialization & nullables

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#2823]
Currently there is partial support for nullable datafields in yaml, where things like nullable structs, enums, etc are supposed to be able to use the special "null" string in yaml to set something to null. However when writing null values, that just gets converted to an empty `MappingDataNode`, instead of a value data node with that special string "null". So you can read nulls, but not write them. Also, nullable custom type serializers currently just don't work when reading.

I started working on a fix, but might take some time before I get around to finishing it. If someone else wants to have a look, then afaik [this branch](https://github.com/ElectroJr/RobustToolbox/tree/serialization-manager-null) fixes some of it, but still needs some issues with nullable generics gets fixed

**Comment by PaulRitter** [comment]
the problem nullability isnt implemented sanely for the most part in serv3 is due to c# not (yet) allowing unconstrained generic types to be nullable. Ontop of that, nullability currently isnt considered in typeserializers, i didnt know there was a demand to (de)serialize only the nullable variant of a type.

In the case of the empty mappingdatafield: this was an intentional design decision, since empty nodes will just not get written during serialization, essentially making it a null value. we can argue about changing the no-data return to an actual nullpointer tho, im open to it.

**Comment by PaulRitter** [comment]
the enum & struct thing seems like an oversight, i'll look into it soon:tm:

**Comment by ElectroJr** [comment]
#3027 & #3026
