### ISSUE TITLE
Cannot serialize entities with missing components.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#2824]
Currently map saving will compare an entity with its prototype and remove any unmodified components, and then serialize/save any modified components.

The problem with this is that if an entity somehow lost a component, there is currently no way of specifying that the entity is supposed to not have that component anymore. So there probably needs to be some way of explicitly excluding certain components in yaml.

Might also be nice for some entity prototype inheritance situations were you want to inherit everything except for a specific component.

**Comment by PaulRitter** [comment]
in comp writing logic, i think we need to differentiate "all comp values were default so we didnt write it" and " the comp was removed"

iirc this already happens, since if the comp is removed, no mention of it exists, but if its all default there will still be a - type node. will have to investigate.
