### ISSUE TITLE
Esoteric serv3 issue

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3039]
https://github.com/space-wizards/space-station-14/runs/7304111972?check_suite_focus=true

Randomly get this on starting up the game.

@PaulRitter

**Comment by PaulRitter** [comment]
after a bit of digging, this seems to be due to CustomHashsetSerializer wrongfully being annotated as a default typeserializer, causing a double registration for HashSet<T>.

as for how to disallow this, i propose the following solutions:
- ~~error on multiple subscriptions to the same combination (here: hashset<t>, sequencedatanode)~~ nvm, this already happens, its just not throwing. (which didnt trigger in the provided example, huh)
- error if a default typeserializer gets registers where the argcount of the typeserializer doesnt match the type itself
