### ISSUE TITLE
WorldBounds rounding issues

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3236]
Explosion Overlays don't extend across the entire viewport.

**Comment by ElectroJr** [comment]
The issue is just that explosions check if the tile centre lies inside of the bounds, not if any part of the tile does, leading to visual pop-in when moving around. So this isn't an engine / general world bounds issue.

The overlay should get fixed by space-wizards/space-station-14/pull/11074, which just enlarges the bounds a bit.
