### ISSUE TITLE
Broadphase related exceptions

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#3402]
- server-side Index out of bounds while processing `DeparentAllEntsOnTile()`
  - AKA `child1 == Proxy.Free` 
  - Can reliably be caused by just doing a  `/explosion 100000` somewhere on station
- Various bugs that can be triggered by just placing "space" tiles randomly around the station. Which one gets triggered first seems somewhat random.
  - (client-side only?) null broadphase while updating physics contacts
  - (client-side only?) Infinite loops (#3395)
  - (client-side only?) Entity with `CanCollide = false` in the physics trees.
  - (client-side only?) Same index out of bounds as the server's `DeparentAllEntsOnTile()`, seemingly caused by an entity leaving PVS?

**Comment by metalgearsloth** [comment]
One side thing I noticed is that on DetachParentToNull an entity recursively updates its children during deletion which is also some duplicate work.

**Comment by metalgearsloth** [comment]
So if anyone else wants to help, the issue is that there's a desync between GetBroadphase and the data the entity's stuff is actually on. This means it will remove proxies for a graph it's not on so any time an entity is going from one broadphase to another it has a high chance of desyncing.

Previously we shitcoded around ordering issues by just storing the broadphase component on entities.

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/199240081-0fe16406-91e9-4267-a89f-ad34e8f39113.png)

Just got one on 0.59.0.0

On my mob's FindContacts it threw the assert for the flare gun not being collidable.

![image](https://user-images.githubusercontent.com/31366439/199240356-993f1725-e8cd-405a-8b8b-d71d15fa4ae0.png)
