### ISSUE TITLE
norot debug assert's uid is off by 2 

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/RobustToolbox#3925]
i was doing a little trolling then i get this message and many like it:

```
[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: NoRot entity has a non-zero local rotation. entity: RD's potted plant (770, PottedPlantRD)
```

so i go to investigate...
but entity 770 is a block game arcade, the actual potted plant is 768!

maybe ToPrettyString is evil i dunno

**Comment by ElectroJr** [comment]
Any more info on what this :trollface:ing involved? Cause it should be impossible for the uid to be off by 2 in that assert.

**Comment by deltanedas** [comment]
saltern trolling :trollface:

it had like 800 norot things with rot set in the original version

**Comment by ElectroJr** [comment]
Ah yeah if you're loading a map file from before that assert was added you have to fix it by just removing the rotation from the maps.

> but entity 770 is a block game arcade, the actual potted plant is 768!

Were you looking  in-game or by reading the map yaml? because the in-game UID is unrelated to the UIDs used in the map file (otherwise you'd never be able to load more than one map into the game)

**Comment by deltanedas** [comment]
> because the in-game UID is unrelated to the UIDs used in the map file (otherwise you'd never be able to load more than one map into the game)

oh i thought the assert gave map uid for some reason pro
