### ISSUE TITLE
PVSSystem assert

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3929]
I tripped line 758 (the tree rootnodes one) locally but haven't seemed to be able to repro it since:

1. Start 2 clients
2. Turn into aghost and have one follow another
3. Move the followed one to another map (in my case planetmap)
4. Try to move it back and get the debug assert getting spammed.

If PVS refactor ends up working out this may be a non-issue.

**Comment by ElectroJr** [comment]
You can reproduce it consistently by:
- Start & connect two clients
- turn the first client that connected into a ghost
- move the ghost off and on station while in PVS range of the other player
- Get assert failure because `cache.Value.tree.RootNodes.Count == 0` for the second player.

AFAIK this bug doesn't actually have any noticeable effect other than triggering this debug assert.
