### ISSUE TITLE
Cannot edit sprite components from the server.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#441]

**Comment by clusterfack** [comment]
This makes some shit really awkward, the server sprite components should be authoritative over the client ones

**Comment by PJB3005** [comment]
Personally I also think we need a way to disable syncing of sprite and light components between client and server, so that the client can be fully authorative too. For stuff like animations.

**Comment by clusterfack** [comment]
Well I think the client door example is a good example of what we *dont* want to do.

We shouldn't need to have the server sent a net message to a client component so that client component will then modify the sprite.

I think you're worried about a whole different beast than that though, which may have a useful implementation in the future but the code we're using right now is bloated and failure prone.

**Comment by PJB3005** [comment]
Yeah of course, we definitely want both. Just saying.
