### ISSUE TITLE
Grid rendering does not take grid offset into account.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#464]
See https://github.com/space-wizards/space-station-14/blob/bde4a01bb88aadc0f798688c8357e28e6284b0c7/SS14.Client/Map/MapRenderer.cs#L31

**Comment by clusterfack** [comment]
Nothing takes grid offset into account when rendering right now. Neither objects nor tiles.

Ostensibly the system should be changed so that each grid renders separately, and then the final product after rendering the relevant portion of a grid gets translated/rotated into the proper position for the final render. I didn't want to make pointless changes to the rendering pipeline before we started any heavy changes like robust or mike though.

**Comment by PJB3005** [comment]
Clyde does do this. Whoo.
