### ISSUE TITLE
Keybinds will break your game if you have old loadout (invalid) values

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/RobustToolbox#4898]
## Description

This was an issue for a while but now became more apparant as of recently.

space-wizards/space-station-14#21352 replaced the bind from "Loadout0-9" to "Hotbar0-9". Players having remendants of "Loadout" in their keybinds expirience issues. I swear i remember having a debug assert months ago about this too

**Reproduction**

https://discord.com/channels/310555209753690112/1176862211482849384/1207242116170780672

1. Have loadout in your keybinds.yml
2. Go to keybindings menu
3. First you will notice all the reset buttons have light up,... this is not normal from what know
4. Press reset
5. Experience issues. if you are on release you wont crash but your settings menu will bug out and potentially other pr's. If you are on debug you will get debug asserted

**Screenshots**

**Additional context**

Fix is to remove the loadout entries or reset your keybinds

space-wizards/space-station-14#25210 releated
https://github.com/space-wizards/RobustToolbox/pull/4841 potencially a culprit for why its worse now. But this always existed apparently since the loadout pr.

![image](https://github.com/space-wizards/RobustToolbox/assets/34938708/a432609c-60f4-41c5-9b25-b928bbe3e59d)

keybinds to replicate 
[keybinds.yml.txt](https://github.com/space-wizards/space-station-14/files/14281257/keybinds.yml.txt)

**Comment by VasilisThePikachu** [comment]
Potencial engine pr needed

**Comment by VasilisThePikachu** [comment]
This effects the ui in general. Not just keybinds... Got no idea how those two are interfering

**Comment by Errant-4** [comment]
On Linux, what happened is all my secondary binds got replaced with the default primary. In many cases, this means I have the same key bound twice
![Screenshot from 2024-02-15 09-53-08](https://github.com/space-wizards/RobustToolbox/assets/35878406/7a661e12-4fcb-43c0-8d56-2cae1c046df6)
![Screenshot from 2024-02-15 09-57-05](https://github.com/space-wizards/RobustToolbox/assets/35878406/b587c463-f8bd-493c-95ff-068e7cdb512c)

This is directly responsible for breaking the UI, because when I press a key, it will be executed twice. This is testable even without the bug messing up your config, because you can double-bind a key as both the primary and secondary.


# Reproduction:
Bind Escape as both primary and secondary "Close recent window or toggle game menu"
Press Esc 
Nothing happens (I assume the window opens and closes on the same frame)

Click the GUI element to open the menu
Press Esc
Menu window closes and immediately reopens

Bind F11 as both primary and secondary "Toggle fullscreen"
Press F11
Window changes fullscreen state then immediately goes back

**Comment by Errant-4** [comment]
Okay the same thing **keeps** happening on both Linux and Windows, deleting my keybinds does not permanently solve the issue, it's not caused by old keybind files conflicting with something. If I modify the keybinds in even the slightest way, then on the next startup all secondaries will be overwritten with the default primaries, duplicating key UI binds as I noted earlier

**Comment by VasilisThePikachu** [comment]
> On Linux, what happened is all my secondary binds got replaced with the default primary. In many cases, this means I have the same key bound twice ![Screenshot from 2024-02-15 09-53-08](https://private-user-images.githubusercontent.com/35878406/305010915-7a661e12-4fcb-43c0-8d56-2cae1c046df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDE3MzAsIm5iZiI6MTcwODAwMTQzMCwicGF0aCI6Ii8zNTg3ODQwNi8zMDUwMTA5MTUtN2E2NjFlMTItNGZjYi00M2MwLThkNTYtMmNhZTFjMDQ2ZGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEyNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMmI4NmNlZTYyMzNmNDljYjkxYjUyYTIyMWYzMTVlMDZhOWRlNjliYTViY2VmZDRlOGExODEyNTQwMTY1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SOHyz8RTrjs3B_fuOPOfIXm5AGuN4fpq90CHgnAgno4) ![Screenshot from 2024-02-15 09-57-05](https://private-user-images.githubusercontent.com/35878406/305011901-b587c463-f8bd-493c-95ff-068e7cdb512c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDE3MzAsIm5iZiI6MTcwODAwMTQzMCwicGF0aCI6Ii8zNTg3ODQwNi8zMDUwMTE5MDEtYjU4N2M0NjMtZjhiZC00OTNjLTk1ZmYtMDY4ZTdjZGI1MTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDEyNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjExMjA2MjM3MDNjZDc1YzI2MDg0ZTkzNTNmN2E2YmU5MTdiM2YxMDM5OTdjODk1ZjY3YmNiNDEwNTMyYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nf4dvKBsznTRLHAm5AJPAvzoOIn7vkpdv_s37z1IEJU)
> 
> This is directly responsible for breaking the UI, because when I press a key, it will be executed twice. This is testable even without the bug messing up your config, because you can double-bind a key as both the primary and secondary.
> # Reproduction:
> 
> Bind Escape as both primary and secondary "Close recent window or toggle game menu" Press Esc Nothing happens (I assume the window opens and closes on the same frame)
> 
> Click the GUI element to open the menu Press Esc Menu window closes and immediately reopens
> 
> Bind F11 as both primary and secondary "Toggle fullscreen" Press F11 Window changes fullscreen state then immediately goes back

I think this is an unrelated issue. This just causes general inconveniences and should be a separate issue. 

My issue debug asserts debug clients, and causes wierd ui issues and broken key binds in release clients

Its also a problem on all operating systems
