### ISSUE TITLE
CompIdx thread contention

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#5230]
At least that's what I think this is.

![image](https://github.com/space-wizards/RobustToolbox/assets/31366439/250f5a32-8d02-425f-86e4-830102ebe77f)

Ideally we'd just cache it upfront I guess?

**Comment by ElectroJr** [comment]
~~!Is there some code in CM14 that uses `Index(Type t)` instead of the generic `Index<T>()`?~~

NVM its used when raising events & starting entities, Rider was just lying to me.
I guess it should be changed to use a frozen dictionary around the same time that `EntityManager._entTraitDict` gets frozen?

**Comment by PJB3005** [comment]
![image](https://github.com/space-wizards/RobustToolbox/assets/8107459/b4b4b60a-1b5f-4224-af37-57283acc487a)

`EntityManager.GetComponentState` is probably the big one.

**Comment by ElectroJr** [comment]
Ah right forgot about that one as well
