### ISSUE TITLE
Standardize coordinate system & angles.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#546]
*Oh god everything's a mess*.

Right now the coordinate system is a complete mess. X+ being to the right (in a default camera situation) is agreed upon, but half the code treats Y- as down and rendering treats Y+ as down. We should standardize it so Y+ is down (in line with Godot and many others).

There's also the issue that angles are a mess. They're coded with a pure mathematical trig circle right now, Y+ being up and 0 degrees being to the right (1, 0). East doesn't make much sense for this, IMO. So we should either standardize it to south or north.

@Acruid

**Comment by PJB3005** [comment]
Alright I wanna get this shit done, especially because we once again messed this up and the code is borked now.

# Coordinates

## 2D

There's a clear disagree on whether 2D should be Y+ down or Y- down. Just to keep things in mind, Y+ UP is a **right handed** coordinate system, Y+ down is a **left handed** coordinate system.

For 2D, technically left handed makes more sense, and Godot follows this. This is because left handed is normal for screen coordinates. This also holds true for OpenGL's window coordinates. For this reason I think the GUI system should stay flat left handed no matter what.

BYOND and things like Unity use a right handed coordinate system in 2D (but BYOND is a turd and Unity's 2D system is pretty akward). Just keep that in the back of your heads. It may be easier for coders to grasp right handed 2D, but I don't think it should be considered.

Great so what's the problem just go with right handed? Right?

## 3D

In 3D, *right handed* is standard. Yay. Godot specifically follows [OpenGL's recommendations](https://www.khronos.org/opengl/wiki/Coordinate_Transformations), which is Y+ is up, X+ is to the right and Z+ is "into your face" and Z- moving "away" from you, assuming no camera rotation. Unity has the Z axis inverted making it left handed. *Seriously though just go right handed it makes more sense and is standard.*

Personally I'm fine with either, especially because OpenGL compliance is nice and Godot compliance is also nice, but...

## Mixing 3D and 2D

So... we wanna be able to use the SS14 engine in both 2D and 3D, but there's a clear disconnect between left and right handed.

So the question for 2D comes down to "do we make entity space right handed, and keep GUI left handed" vs "do we completely ruin 3D and make it left handed."

That said, just making 2D right handed isn't a perfect solution. We imagine 2D as "top down" of course, so Y is *north/south* and X *east/west*. Both of those are "horizontal" if you were to map it to a 3D space like we want to. Problem is Godot's/OpenGL's 3D space makes Y vertical. The problem is visible in Cluster's [WiP 3D video](https://old.reddit.com/r/ss14/comments/8qpx5p/extremely_early_wip_3d_feature_showcase_by_cluster/). The human is pointing "up" vertically which is correct. Everything would have to be rotated by 90 degrees! So either we silently "rotate" everything by 90 degrees, which pretty much is equivalent to making our own coordinate system for 3D. Or we make 3D and 2D coordinates completely separate, at which point we might as well keep 2D left handed. 

Personally I see 2 solutions:
1. Make 2D entity-space right handed (but keep GUI left handed), and use Z+ vertical in 3D. Then we can treat use 3D coordinates in the 2D engine by just "ignoring" the Z coordinate, so to speak.
2. Keep 2D entirely left handed, and and use Godot's 3D coordinate system for 3D. This means 2D/3D coordinates are NOT easily interchangeable which might be a major pain if we want to write code that's shared among both. That said 2D/3D both use the "best" coordinate system for their use case. I wanna say that this seems like a really big maintenance problem at first glance.

## Angle

Oh yeah, `Angle` is a purely cartesian unit circle right now, meaning it's right handed. Even if we do go right handed, 0 degrees/radians being East makes no sense. I'd make much more sense if an `Angle` of 0 in 2D pointed south.

Thoughts?

**Comment by RemieRichards** [comment]
Got the email while at work so didn't read the whole thing originally.
But you've already stated my opinion which is:

GUI left handed
Entity space right handed

**Comment by PJB3005** [comment]
@RemieRichards any opinion on the 3D coordinate space?

**Comment by RemieRichards** [comment]
right handed

**Comment by ShadowCommander** [comment]
I say we should go with right handed for 2D and 3D with GUI as left handed.
Most engines I've seen have Angle 0 point East. There are a few that point North, but I don't think I've seen any that point South.

**Comment by PJB3005** [comment]
@ShadowCommander any examples on the angle thing?



Also I'd still like an opinion on what the exact coordinate system should be in 3D, besides right handed (whether Z+ or Y+ is up)

**Comment by RemieRichards** [comment]
Y+ is up, Z+ towards you

**Comment by captkirk88** [comment]
Y is towards you, Z is diagonal.

**Comment by Acruid** [comment]
**ENGINE**
* N/E/S/W cardinal directions are completely dependent on camera orientation. They should not be used in the world space.
* A 0 degree angle should be +X because math.
* Rotation I would arbitrarily decide to be counter-clockwise, because I like using right-handed coordinate systems.
* +Z should be Up (away from gravity) so it can easily be ignored in 2D.
* The three basis vectors therefore are +X (Forward), +Y (Left), +Z (Up).
* I also am going to want to use a right handed system so that somebody does not have to change all the helper functions in our math library.

**UI/Screen Space**
* UI will continue to exist in the default 2D left-handed screen coordinates that Godot uses, both for 2D and 3D.

**2D**
Note that for 2D Godot uses the same camera orientation for world space and screen space. This allows the distinction between the two to blur, resulting in things like using cardinal directions, and game logic to make a lot of assumptions. Ask about how amazing CluwneLib was in Discord for more info.

It does not matter where the origin is in Godot 2D screen space. It is trivial to build a transform matrix to go from Engine world space to Godot 2D world space. Its not like the grids are restricted to a quadrant of the engine world, so idk why this was brought up.

Since Godot uses a left handed coordinate system for 2D, all positions and rotations will have to be transparently converted from right to left handed coordinates between the Engine and Godot. There is no instance where game logic will need to care about how the WorldToScreen/ScreenToWorld transforms do this, because the game simulation should have no knowledge of Godot.

**3D**
Godot uses a right hand coordinate system for 3D. By changing the camera orientation in Godot the Engine world space should be able to easily match up with Godot's 3D world space. It should be straight forward to set up a transform matrix on the boundary between the two that changes all the matrices so that +Z in the Engine is +Y in Godot. This will make Cluster's life much easier.

**Comment by PJB3005** [comment]
See #691, 2D is now right-handed.

I'm not closing this issue yet, though.

**Comment by Acruid** [comment]
This discussion seems finished, so I am going to close this. We are not even using Godot anymore.

For the final decision (and what we are currently using, because we are NOT changing this again):
* The game world is using 2D right-handed coordinates. This is all the Transform and Angle values you are working with in content. This is the math you learned in school, where the unit circle rotates counterclockwise as theta increases. The camera is oriented so that it is looking down the -Z axis at the X/Y plane that all of the entities exist on. The "Up" direction (forward face of the X/Y plane) of the world is +Z. All rotations rotate around the Z axis.
* The UI uses 2D left-handed coordinates, with the origin at the top left, +X going to the right, and +Y going down. Rotations go clockwise. Exactly like any other UI library.
* Generally you do not need to worry about how Clyde works internally, or how Clyde works with OpenGL.
