### ISSUE TITLE
Make GUI HIDPI aware.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#733]
The GUI system does not at all work properly on high DPI screens. While the font system can draw at higher DPIs, general UI layout isn't even remotely aware and will just break.

I actually found this [documentation page for Rust `glutin`](https://docs.rs/glutin/0.17.0/glutin/dpi/index.html) quite useful.

Basically I'm thinking of having a single DPI factor across the entire client, and it CAN change.

I'm not sure how much we should put the burden of DPI on the GUI controls though. Ideally you shouldn't have to worry too much as a content coder. Some possibilities:

1. GUI coordinates are in logical pixels, so not DPI aware. While rendering these coordinates get up scaled to be DPI aware. I think this solution might end up with poor scaling though, especially on fractional DPI values. The advantage of course is that controls care VERY little about actual DPI changes and such.
2. Expose both DPI-scaled and physical pixel sizes to the GUI system, and discourage usage of physical pixel sizes. This way layout systems can be DPI aware to produce optimal layout even on fractional sizes, while you generally don't have to care too much. This is probably the best option.
3. Physical pixels only, but still expose DPI values and events to change them. Probably the worst idea because people WILL mess it up or straight ignore it.

**Comment by Acruid** [comment]
https://www.factorio.com/blog/post/fff-277
This goes into some detail about how Factorio solved scaling in the GUI. Personally I would abstract physical pixel units as far away from controls as possible so all positioning uses the DPI-scaled units.

**Comment by PJB3005** [comment]
Factorio's solution does seem like it's pretty good I'd say.

Personally when writing this I WAS thinking about the problem of "1 px gap with a 125% scale", but I figured that those kinda gaps weren't significant enough. I don't have any reference to work with though so it might be a problem yes.

A consideration I don't see mentioned in the FFF:
1. At something like a 125% scale, how should nine patches for GUI elements scale? Of course in either case we'd have versions of boxes for multiple scale levels but I don't think it's a good idea to provide them for EVERY scale level.
    1. Stretch them anyways. This comes with the issue of blurry stretching.
    2. Only stretch the center, so their edges will appear smaller but they'll still be sharp.

**Comment by PJB3005** [comment]
UI scaling is in. It doesn't auto match desktop settings or anything but it's there.

**Comment by slashdevslashurandom** [comment]
Proper DPI / UI scale awareness on different OSes would be very beneficial.

Right now I'm using a display that runs at a x2 scale, but its resolution is not a full 4K. On Linux/Wayland, applications that support scaling run at their proper scale, whereas ones that don't are automatically upscaled.

In my case, this means that this engine runs at a practical resolution of 1440x900 rather than 2880x1800, and the viewport and the UI end up being rather cramped. I could set viewport scaling to x1 rather than x2 and reduce the UI scale, but that would make everything too small instead.

If the app supported detecting UI scale and running at the proper resolution, I could set viewport scaling to x3 and get a good balance between things being too small to see and too cramped to use.

**Comment by PJB3005** [comment]
That's because we're still using GLFW on Linux, which is running through XWayland. It'll be fixed when we switch to SDL3, whenever that'll happen.
