### ISSUE TITLE
CSFML Segfaults on Linux while loading shaders

### ISSUE THREAD

**Issue by BobdaBiscuit** [space-wizards/RobustToolbox#76]
I have no idea how to report this properly so here's the stacktraces.

https://pastebin.com/44vZtUF6

**Comment by d34d10cc** [comment]
I suspect this to be related to zip-file corruption since other people have used the project on Linux and it worked completely found. I also found nothing that could be causing this in the code.

That said, if zip-file corruption is the culprit here, the code needs a way of throwing an exception instead of just segfaulting.

**Comment by BobdaBiscuit** [comment]
It isn't zipfile corruption since we are all using the same one.

The problem line is 
"loadedShader = new GLSLShader(VertexShader, FragmentShader);" in ResourceManagerZip.cs

**Comment by ZoldorfTheWizard** [comment]
That line of code takes the frag and vert shader and compiles it. From the stacktrace it looks like it fails to compile. Bobda, can you debug step through this to the point just before the crash and tell me the contents of String Vars VertexShader and FragmentShader? They should be a path to the shader. i suspect it is the black.vert and black.frag shader failing to compile on linux due to a incorrect path to the zip file but i may be wrong.

**Comment by d34d10cc** [comment]
I'll try to reproduce the problem today and see if I can fetch the values you asked for.

**Comment by BobdaBiscuit** [comment]
@Silvertorch5 
'Shaders/Black.frag'
'Shaders/Black.vert'
'System.IO.MemoryStream' 'System.IO.MemoryStream'

**Comment by ZoldorfTheWizard** [comment]
Tested this on latet Arch Linux. game runs and the shaders do not crash. closing
