### ISSUE TITLE
Serialization v3

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#891]
The current serialization system, `ExposeData`, has a lot of shortcomings:

1. Serialization happens *on* an instance of a component (or somehow nested) in most cases. This makes it basically impossible to sanely validate prototypes without instantiating them, or doing any sort of automatic operation on prototypes at all for that matter.
2. Data is continuously re-parsed from YAML. This is incredibly slow and also means we're forced to keep the YAML data round, which is also very memory intensive (Most of the server managed heap memory while I am writing is in fact the parsed YAML tree). There are some mechanisms in the current exposedata system to do caching. It's all ugly.

I hereby propose the following for serialization v3:

Data is (de) serialized into an "intermediate" parsed class. This class can then be cheaply copied (deep copies perhaps necessary for certain components) into the component when the component is instantiated. Being a separate class with little logic, this data can then also be acted upon more easily by tooling to automatically very whether it is indeed sane.

To avoid drowning in boilerplate, it is probably best if there were attributes that could be applied to various things like component properties to automate all of this.
Various things like dynamic code generation can also be used to improve performance of these automatic attributes.

**Comment by Ygg01** [comment]
@PJB3005 Let's do this then.

>To avoid drowning in boilerplate, it is probably best if there were attributes that could be applied to various things like component properties to automate all of this.

Are these existing attributes? Or something I'd need to make first?

>Various things like dynamic code generation can also be used to improve performance of these automatic attributes.

Are there any examples of dynamic code generation in C# I could use?

**Comment by PaulRitter** [comment]
> > To avoid drowning in boilerplate, it is probably best if there were attributes that could be applied to various things like component properties to automate all of this.
> 
> Are these existing attributes? Or something I'd need to make first?

He means actual C#-Attributes, which you could slap onto Fields to mark then to be filled by parsed data. https://docs.microsoft.com/de-de/dotnet/csharp/programming-guide/concepts/attributes/
The Idea here would probably be to have a `[MappedValue<T>("myyamltag")]` attribute, altough i don't know if you can make attributes generic, might have to pass T as a Type-Definition as a parameter.

> > Various things like dynamic code generation can also be used to improve performance of these automatic attributes.
> 
> Are there any examples of dynamic code generation in C# I could use?

IoCManager & Componentdependencies use this method. They basically construct a method per Type to automatically fill all field which were marked with the aforementioned attribute.

If you want help on this I can help you too, since I (with alot of help from pjb) wrote Componentdependencies.

**Comment by PaulRitter** [comment]
Followup: Attributes cannot be generic, altough you wouldn't really have to pass a type, since it could just be able to grab the fields type

What the Attribute should have tho is:
- yaml-tag, obviously
- a bool indicating if it should be written too
- (custom read/write function)

Also use Componentdependencies as an example, since they do reading/writing, while the IoCManager only does writing.

**Comment by PaulRitter** [comment]
Can you assign this to me? I'll do this when traitor (&physshaperect tests) are done

**Comment by metalgearsloth** [comment]
> 
> 
> Can you assign this to me? I'll do this when traitor (&physshaperect tests) are done

Thy will be done.

**Comment by Ygg01** [comment]
Look forward to this mangz :D

**Comment by PJB3005** [comment]
Yes, this is absolutely not for the faint of heart and I definitely would not recommend you take this upon yourself @Ygg01 since I know you're quite new to .NET and our code base.

I want to restate that I want the following goals achieved by this rewrite:

1. Accessibility of the deserialized data without needing to instantiate a component and `.ExposeData()` it. This is for tooling and also cases such as the entity spawn window dumping icons.
2. Improved performance by avoiding constant re-parsing of YAML data on entity spawn. Parsing should only be happening during prototype and map load. This also allows us to drop the heavy `YamlDotNet` AST which currently has to be kept around in memory.
3. Convenience so that we don't have to manually write `ExposeData` calls anymore. Attributes pls.

**Comment by PaulRitter** [comment]
Unassigning myself due to working on Codebehind XAML-UI

**Comment by Acruid** [comment]
![image](https://user-images.githubusercontent.com/1685952/109055790-7845a680-7694-11eb-91ab-ab638323dbfd.png)

**Comment by PaulRitter** [comment]
![image](https://user-images.githubusercontent.com/16618384/109273983-37c06700-7813-11eb-9327-12e059b3c57d.png)

**Comment by DrSmugleaf** [comment]
Done in https://github.com/space-wizards/RobustToolbox/pull/1606 22 DAYS EARLIER LETS GOOOOOOOOOOO
