### ISSUE TITLE
Simplify RSI format?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#906]
Right now the RSI format has a bunch of unused stuff specified, namely selectors and flags. Neither are used. Also the format could just generally be easier to write by hand.

The idea behind selectors was that they could work like movement states do in BYOND. The idea behind flags is that they could be special flags the code could read. Would it make sense to get rid of these to simplify the code?

**Comment by io-june** [comment]
I found working with RSI manually is not much pleasant job. I had better times just converting DMIs into RSIs, but as we also kind of revisiting structures of sprite sheets, I've figured an easiest way to create a sheet i need:
1)just make new DMI in Dream Maker
2)copypaste states from existing DMIs 
3)edit them in Dream Maker
4)convert into RSI
RSI is pretty much readable format, the issue is that dmi2rsi converter doesn't really format the text, leaving it all in a single line, and i think my json beautifier doesn't do a good job at formatting it by itself.

**Comment by RemieRichards** [comment]
So what you're saying is we need a standalone RSI editor
🤔

**Comment by metalgearsloth** [comment]
Could make it yaml for consistency with the prototypes and to make it easier to read as you don't need to explicitly format it nicely like with json.

I don't really have dramas with scripted conversions of dmi to rsi, and using the vscode formatter makes it look fine when I do need to look at it.

It would be nice to have a unit test telling you about invalid rsis and what's wrong specifically.

**Comment by PJB3005** [comment]
One reason to not use YAML is because it can't be as easily parsed by tooling. Python for example has native JSON support but no native YAML support.

This is of course not an issue when writing our own tools, but if we were to make something like a Krita plugin or whatever (Python) it might be a problem.

**Comment by metalgearsloth** [comment]
True true, whenever I use a python yaml tool to bulk create prototypes I die a little inside.

**Comment by d34d10cc** [comment]
I'd like this assigned to me, please.

**Comment by PaulRitter** [comment]
should this still be open? @PJB3005
